print('회원 정보를 입력하세요.')
userName = input('이름:')
userMail= input('이메일:')
userID = input('ID:')
userPW = input('PW:')
print('----------------------------------------------------------------------------------------')
print('To. ' + userMail)
print('→ 아이디 및 비밀번호 확인')
print(userName + '고객님 안녕하세요')
print(userName + '고객님의 아이디와 비밀번호는 아래와 같습니다.')
print('ID : ' + userID)
print('PW : ' + userPW)
print('----------------------------------------------------------------------------------------')